require('dotenv').config();
const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({ ok: true, service: 'future-minds-backend' }));
app.use('/auth', require('./routes/auth'));
app.use('/requirements', require('./routes/requirements'));
app.use('/teachers', require('./routes/teachers'));
const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log(`Future Minds backend running on http://localhost:${PORT}`));
